
 CREATE TABLE ORDERS(ORDER_ID INTEGER PRIMARY KEY auto_increment,
 ORDER_DATE DATE,
 ORDER_STATUS VARCHAR(20));
 CREATE TABLE ITEM(ITEM_ID INTEGER PRIMARY KEY AUTO_INCREMENT,ORDER_ID INTEGER,
 ITEM_NAME VARCHAR(50),
 ITEM_UNIT_PRICE DOUBLE,
 ITEM_QUANTITY INTEGER,
 FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID));
